
package schemas.dynamics.microsoft.codeunit.postcodeinfo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PostCodeInfo", targetNamespace = "urn:microsoft-dynamics-schemas/codeunit/PostCodeInfo", wsdlLocation = "http://hp17:7057/NAV2016_WebService/WS/Codeunit/PostCodeInfo")
public class PostCodeInfo
    extends Service
{

    private final static URL POSTCODEINFO_WSDL_LOCATION;
    private final static WebServiceException POSTCODEINFO_EXCEPTION;
    private final static QName POSTCODEINFO_QNAME = new QName("urn:microsoft-dynamics-schemas/codeunit/PostCodeInfo", "PostCodeInfo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://hp17:7057/NAV2016_WebService/WS/Codeunit/PostCodeInfo");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSTCODEINFO_WSDL_LOCATION = url;
        POSTCODEINFO_EXCEPTION = e;
    }

    public PostCodeInfo() {
        super(__getWsdlLocation(), POSTCODEINFO_QNAME);
    }

    public PostCodeInfo(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSTCODEINFO_QNAME, features);
    }

    public PostCodeInfo(URL wsdlLocation) {
        super(wsdlLocation, POSTCODEINFO_QNAME);
    }

    public PostCodeInfo(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSTCODEINFO_QNAME, features);
    }

    public PostCodeInfo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PostCodeInfo(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PostCodeInfoPort
     */
    @WebEndpoint(name = "PostCodeInfo_Port")
    public PostCodeInfoPort getPostCodeInfoPort() {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/codeunit/PostCodeInfo", "PostCodeInfo_Port"), PostCodeInfoPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PostCodeInfoPort
     */
    @WebEndpoint(name = "PostCodeInfo_Port")
    public PostCodeInfoPort getPostCodeInfoPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:microsoft-dynamics-schemas/codeunit/PostCodeInfo", "PostCodeInfo_Port"), PostCodeInfoPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSTCODEINFO_EXCEPTION!= null) {
            throw POSTCODEINFO_EXCEPTION;
        }
        return POSTCODEINFO_WSDL_LOCATION;
    }

}
